"""Render an offline report from measured BIRDS telemetry analysis."""
import html
import json


def render(result, manifest):
    sats = result["satellites"]
    rows = "".join(f"<tr><td>{html.escape(name)}</td><td>{v['passes']}</td><td>{v['samples']:,}</td><td>{v['median_solar_mean_w']:.3f}</td><td>{v['median_solar_energy_wh']:.3f}</td><td>{v['min_battery_v']:.2f}–{v['max_battery_v']:.2f}</td><td>{v['flagged_passes']}</td></tr>" for name,v in sats.items())
    passes = sorted(result["passes"], key=lambda x:x["solar_energy_wh"])
    pass_rows = "".join(f"<tr><td>{html.escape(p['satellite'])}</td><td>{html.escape(p['pass'])}</td><td>{p['duration_min']:.1f}</td><td>{p['solar_mean_w']:.3f}</td><td>{p['solar_p95_w']:.3f}</td><td>{p['solar_energy_wh']:.3f}</td><td>{p['battery_net_terminal_wh']:+.3f}</td><td class={'flag' if p['health_flags'] else 'ok'}>{html.escape('; '.join(p['health_flags']) or 'No rule flag')}</td></tr>" for p in passes)
    chart = "".join(f"<div class=bar><span>{html.escape(n)}</span><i style='width:{min(100,v['median_solar_mean_w']/max(x['median_solar_mean_w'] for x in sats.values())*100):.1f}%'></i><b>{v['median_solar_mean_w']:.3f} W</b></div>" for n,v in sats.items())
    source_url = manifest["repository"] + "/tree/" + manifest["commit"]
    return f'''<!doctype html><html lang=en><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>OrbitBench Flight Data</title><style>
body{{margin:0;background:#eef3f4;color:#142733;font:15px/1.55 system-ui}}main{{max-width:1200px;margin:auto;padding:36px 22px}}header{{border-top:7px solid #087f73}}h1{{font-size:46px;margin:12px 0 0}}section{{background:white;padding:22px;margin:18px 0;border:1px solid #d3dfe2;border-radius:9px;overflow:auto}}.notice{{border-left:5px solid #087f73;background:#e5f5f1;padding:17px}}table{{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}}th,td{{padding:9px;border-bottom:1px solid #dfe7e9;text-align:left;white-space:nowrap}}td:last-child{{white-space:normal}}.ok{{color:#087f73}}.flag{{color:#ad3d31;font-weight:650}}.bar{{display:grid;grid-template-columns:110px 1fr 90px;gap:12px;align-items:center;margin:13px 0}}.bar i{{display:block;height:18px;background:#087f73;border-radius:3px}}code{{word-break:break-all}}small{{color:#4c626d}}@media(max-width:650px){{h1{{font-size:36px}}}}</style><main>
<header><small>ASI HACKATHON · CHALLENGE 2 · MEASURED EPS EVIDENCE</small><h1>OrbitBench Flight Data</h1><p>Reproducible health and energy analysis of four BIRDS 1U CubeSats.</p></header>
<div class=notice><b>REAL ON-ORBIT TELEMETRY.</b> Values below are computed from the public BIRDS workbooks pinned at commit <code>{manifest['commit']}</code>. This establishes a functional data-analysis system. It does not turn public telemetry into qualification evidence for a new spacecraft.</div>
<section><h2>Measured fleet overview</h2><div>{chart}</div><table><tr><th>Satellite</th><th>Passes</th><th>Samples</th><th>Median pass mean</th><th>Median energy/pass</th><th>Battery range</th><th>Flagged passes</th></tr>{rows}</table></section>
<section><h2>Every operational recording</h2><p>Positive battery terminal energy means net discharge over the recording; negative means net charge. “Sunlit” is a measured-power proxy, not an ephemeris label.</p><table><tr><th>Satellite</th><th>Recording</th><th>min</th><th>Mean W</th><th>P95 W</th><th>Solar Wh</th><th>Battery Wh</th><th>Health rule</th></tr>{pass_rows}</table></section>
<section><h2>Traceability and use</h2><p>Source: <a href="{source_url}">BIRDSOpenSource/EPS_dataset at pinned commit</a>. The run verifies each workbook hash against the local manifest. Operational sheets are analyzed; TSURU laboratory “Test” sheets are excluded. Incomplete rows are counted and rejected.</p><p>Equations: {html.escape(result['method']['panel_power'])}; {html.escape(result['method']['solar_energy'])}. The original dataset authors define positive battery current as discharge and negative as charge.</p><p><b>Engineering decision:</b> these recordings can train health rules and provide measured EPS envelopes. They do not contain the new mission's payload load, attitude, continuous state of charge, or environment, so a flight design still requires mission-specific telemetry or calibrated hardware-in-the-loop tests.</p></section>
</main></html>'''
