"""Offline engineering evidence report; all design inputs are assumptions."""
import html


def render(before,after,search,assessment,tests):
    def line(result,color):
        trace=result['trace']; points=trace[::max(1,len(trace)//400)]
        if points[-1] != trace[-1]: points.append(trace[-1])
        coords=' '.join(f"{65+650*p['minute']/result['duration_min']:.2f},{265-220*p['soc']:.2f}" for p in points)
        return f'<polyline points="{coords}" fill="none" stroke="{color}" stroke-width="3"/>'
    comparison=''.join(f'<tr><td>{html.escape(a["id"])}</td><td>{html.escape(a["description"])}</td><td class="{"pass" if a["pass"] else "fail"}">{"PASS" if a["pass"] else "FAIL"}</td><td class="{"pass" if b["pass"] else "fail"}">{"PASS" if b["pass"] else "FAIL"}</td></tr>' for a,b in zip(before['checks'],after['checks'])) if after else ''
    corners=''.join(f'<tr><td>{html.escape(c["corner"])}</td><td>{c["min_soc"]:.1%}</td><td>{c["net_battery_wh_per_orbit"]:.3f}</td><td>{c["unserved_wh"]:.3f}</td><td>{"PASS" if c["pass"] else "FAIL"}</td></tr>' for c in assessment['corners']) if assessment else ''
    reserve_y=265-220*before['config']['min_soc']
    candidate_text=f"{after['config']['payload_duty']:.0%}" if after else 'None'
    margin_text=(f"Worst candidate storage surplus: {min(c['net_battery_wh_per_orbit'] for c in assessment['corners']):.4f} Wh/orbit. "
                 'A barely positive surplus is not a comfortable operating margin. Set additional mission margins before accepting a design.'
                 if assessment else 'No candidate met all modeled constraints. Revise the architecture or requirements.')
    after_line=line(after,'#007f75') if after else ''
    params=''.join(f'<tr><td>{html.escape(k)}</td><td>{v}</td></tr>' for k,v in before['config'].items())
    return f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OrbitBench | Engineering decision record</title>
<style>body{{margin:0;background:#f0f2f2;color:#192b37;font:16px/1.6 system-ui,sans-serif}}main{{max-width:1100px;margin:auto;padding:40px 24px}}header{{border-top:7px solid #e67a27;padding-top:22px}}h1{{font-size:48px;margin:5px 0;letter-spacing:-2px}}h2{{font-size:24px}}.label{{font:700 12px monospace;letter-spacing:2px;color:#84502c}}.note{{padding:20px;background:#fff2df;border-left:4px solid #e67a27;margin:24px 0}}section,.card{{background:white;border:1px solid #d6dfe2;padding:24px;margin:20px 0;border-radius:8px}}.cards{{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}}.value{{font-size:38px;font-weight:750}}.muted{{color:#536a76}}table{{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}}th,td{{text-align:left;border-bottom:1px solid #dde4e7;padding:10px}}.pass{{color:#007f75;font-weight:700}}.fail{{color:#b74435;font-weight:700}}svg{{width:100%;height:auto;background:#f8fafb}}code{{overflow-wrap:anywhere}}@media(max-width:650px){{.cards{{grid-template-columns:1fr}}section{{overflow:auto}}h1{{font-size:38px}}}}@media print{{section{{break-inside:avoid}}}}</style>
<main><header><div class="label">ASI HACKATHON · CHALLENGE 02 · DECISION RECORD 001</div><h1>OrbitBench</h1><p class="muted">Locally maintainable CubeSat energy design and verification software</p></header>
<div class="note"><b>ANALYTICAL PROTOTYPE — ASSUMED MISSION INPUTS.</b><br>This report verifies calculations and a bounded design search. It does not establish hardware performance, flight readiness, or a certified TRL. Payload power is averaged; peak-current and scheduling feasibility are outside this model.</div>
<div class="cards"><div class="card">Initial payload duty<div class="value fail">{before['config']['payload_duty']:.0%}</div>Nominal model: {"PASS" if before['all_pass'] else "FAIL"}</div><div class="card">Best feasible grid candidate<div class="value pass">{candidate_text}</div>Under all eight assumed corners</div><div class="card">Software verification<div class="value">{tests['passed']}/{tests['run']}</div>Automated tests passed</div></div>
<section><h2>01 / A measurable design decision</h2><p>The search evaluates 101 duty-cycle values against eight combinations of solar power, eclipse duration, and battery capacity: <b>{search['simulation_count']} simulations</b>. It maximizes modeled payload duty while satisfying energy supply, reserve, and per-orbit sustainability checks.</p><p><b>Tradeoff:</b> reducing payload duty preserves modeled energy reserve at the cost of payload operating time. The mission owner must decide whether the resulting duty meets the payload objective; a feasible energy budget alone cannot answer that question.</p><table><tr><th>Requirement</th><th>Check</th><th>Initial nominal</th><th>Candidate nominal</th></tr>{comparison}</table></section>
<section><h2>02 / Battery reserve over the modeled mission</h2><p><span class="fail">Orange: initial design</span> · <span class="pass">Green: candidate</span> · Dashed: minimum reserve. Both traces show nominal conditions; the next table checks the candidate at all stress corners.</p><svg viewBox="0 0 780 325" role="img" aria-label="Nominal battery state-of-charge comparison"><path d="M65 35V265H735" stroke="#71828b" fill="none"/><path d="M65 {reserve_y}H735" stroke="#71828b" stroke-dasharray="6 4"/>{line(before,'#c56027')}{after_line}<text x="10" y="48">100%</text><text x="22" y="269">0%</text><text x="65" y="302">0 h</text><text x="650" y="302">{before['duration_min']/60:.2f} h</text></svg></section>
<section><h2>03 / Candidate stress evidence</h2><p>S = solar-power multiplier; E = added eclipse minutes; B = battery-capacity multiplier. Levels: S ∈ {{1.0, 0.75}}, E ∈ {{0, 5}}, B ∈ {{1.0, 0.8}}. These are assumed engineering stresses, not measured probability distributions.</p><div class="note">{margin_text}</div><table><tr><th>Corner</th><th>Minimum SOC</th><th>Net Wh/orbit</th><th>Unserved Wh</th><th>Model result</th></tr>{corners}</table><p>If no candidate is feasible, the report shows “None”; that result must never be interpreted as permission to run the payload.</p></section>
<section><h2>04 / What is developed locally</h2><p><b>Delivered source:</b> energy solver, input validation, stress search, requirement evaluation, tests, and offline evidence export. The team can inspect, modify, and rerun this software without a paid API or cloud service.</p><p><b>Proposed next capability:</b> instrument adapters and a university-operated validation bench. Programmable power supplies, loads, calibration instruments, and physical EPS hardware remain external dependencies until verified suppliers and lab access are established.</p><p><b>TRL assessment:</b> provisional TRL 2 → candidate TRL 3 for the software concept only, subject to reviewer acceptance of the proof-of-concept evidence. TRL 4 needs laboratory validation. No TRL change is claimed for a spacecraft or EPS hardware.</p></section>
<section><h2>05 / Configuration and reproducibility</h2><p>Every value is a team-supplied design assumption. Unit definitions and exclusions are documented in the engineering dossier.</p><table><tr><th>Parameter</th><th>Value</th></tr>{params}</table><p>Configuration SHA-256: <code>{before['config_sha256']}</code></p><p>Archive outputs include raw traces, checks, the full search table, automated-test results, and source hashes. Reproduce with <code>python run.py</code>.</p></section>
<section><h2>06 / Next release gate</h2><p>Compare predictions with a calibrated bench dataset under documented load and illumination profiles. Add time-varying payload operation, power/current limits, temperature and aging effects, and equipment uncertainty before making operational claims. A local partner and supplier verification are still required.</p></section></main></html>'''
